### ISSUE TITLE
UnicodeEnocdeError

### ISSUE THREAD

**Issue by overthink** [leonhllai/challenge#1]
Hi Leon.  I'm trying to evaluate your solution, but am getting the following error:

```
$ python sortable.py 
Traceback (most recent call last):
  File "sortable.py", line 65, in <module>
    sortable()
  File "sortable.py", line 59, in sortable
    json.dump(result,ff, ensure_ascii=False)
  File "/usr/lib/python2.7/json/__init__.py", line 182, in dump
    fp.write(chunk)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 44: ordinal not in range(128)
```

Please let me know when you fix this up and I will take another look at your solution.  Thanks!

Mark (from sortable.com)

**Comment by leonhllai** [comment]
Hi, Mark,

It should be running in python3. Sorry, I forgot to mention.

Leon
